In [1]:
# Dependencies
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import pymongo
from pymongo import MongoClient
import os

In [2]:
# Save path to data set in a variable
data_file = "C:\\Users\\taiwo\\OneDrive\\Desktop\\PREWORK_TO\\Module 16\\Project2\\Data Files\\population-density.csv"

In [3]:
# Use Pandas to read data
data_file_pd = pd.read_csv(data_file)
data_file_pd.head()

     COUNTRIES Code  Year  Density
0  Afghanistan  AFG  1961    14.04
1  Afghanistan  AFG  1962    14.32
2  Afghanistan  AFG  1963    14.60
3  Afghanistan  AFG  1964    14.91
4  Afghanistan  AFG  1965    15.22

In [4]:
# ====== Connection ====== #
# Connection to Mongo
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Connection to the database
db = client.Project2

# Connection to the collection
#collection = db.Project2

In [5]:
# Read the row from data_file to create a dictionary
for _, row in data_file_pd.iterrows():
   dic = {
       'Countries':row["COUNTRIES"],
       'Code': row["Code"],
       'Year': row["Year"],
       'Density': row["Density"]
       
       
   }
   #insert dictionary into mongo
   #collection.insert_one(dic)

In [8]:
# ====== Connection ====== #
# Connection to Mongo
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Connection to the database
db = client.Project2

# Connection to the collection
#collection = db.Energy

In [ ]:
# Define database and collection
db = client.Project2
#collection = db.coordinates

In [ ]:
# Dependencies
# from bs4 import BeautifulSoup
# import requests
# import pymongo
# import pandas as pd

In [ ]:

# URL of page to be scraped
# url = 'https://developers.google.com/public-data/docs/canonical/countries_csv'

# # Retrieve page with the requests module
# response = requests.get(url)
# Create BeautifulSoup object; parse with 'lxml'
# soup = BeautifulSoup(response.text, 'lxml')
# row = [abbr.append(i.text[1])for i in td]

In [10]:

# Examine the results, then determine element that contains sought info
# results are returned as an iterable list
# table = soup.find('table')
# table_rows = table.find_all('tr')
# # Loop through returned results
# data = []
# for tr in table_rows:
#     td = tr.find_all('td')
#     row = [i.text for i in td]
#     try:
#         data.append({"abbr": (row[0]), 
#                       "Lat": (row[1]), 
#                       "Lng": (row[2]), 
#                       "country": (row[3])})
#     except:
#         pass

In [11]:
#collection.insert_many(data)

In [12]:
# Save path to data set in a variable
data_file3 = "C:\\Users\\taiwo\\OneDrive\\Desktop\\PREWORK_TO\\Module 16\\Project2\\Data Files\\TEC.csv"

In [13]:
# Use Pandas to read data
data_file_pd3 = pd.read_csv(data_file3)
data_file_pd3.head()

,s/n,country,1990,1991,1992,1993,1994,1995,1996,1997,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,1,Belgium,48,50,51,49,52,53,56,56,...,56,60,56,54,56,53,53,56,55,53
1,2,Czech Republic,50,45,44,43,41,42,43,43,...,43,45,44,43,43,42,42,42,43,43
2,3,France,225,237,234,238,231,240,250,244,...,255,263,254,254,255,244,248,244,244,243
3,4,Germany,355,344,338,335,333,336,348,346,...,310,326,310,311,318,306,308,310,312,301
4,5,Italy,151,155,154,153,151,159,159,162,...,170,174,168,161,156,147,153,151,154,155

In [14]:
# Save path to data set in a variable
data_file4 = "C:\\Users\\taiwo\\OneDrive\\Desktop\\PREWORK_TO\\Module 16\\Project2\\Data Files\\TEP.csv"
# Use Pandas to read data
data_file_pd4 = pd.read_csv(data_file4)
data_file_pd4.head()

,s/n,country,1990,1991,1992,1993,1994,1995,1996,1997,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,1.0,Belgium,13.0,13.0,13.0,12.0,12.0,12.0,12.0,13.0,...,15.0,16.0,16.0,14.0,15.0,13.0,11.0,15.0,15.0,12.0
1,2.0,Czech Republic,41.0,39.0,37.0,36.0,34.0,33.0,33.0,34.0,...,32.0,32.0,33.0,33.0,31.0,30.0,29.0,27.0,28.0,28.0
2,3.0,France,112.0,119.0,120.0,126.0,124.0,128.0,132.0,129.0,...,129.0,136.0,136.0,135.0,137.0,138.0,139.0,131.0,130.0,135.0
3,4.0,Germany,190.0,169.0,164.0,153.0,145.0,145.0,143.0,145.0,...,126.0,129.0,123.0,123.0,121.0,120.0,120.0,116.0,115.0,115.0
4,5.0,Italy,26.0,26.0,28.0,29.0,30.0,30.0,31.0,31.0,...,32.0,33.0,32.0,35.0,37.0,37.0,36.0,34.0,34.0,36.0

In [15]:
# Save path to data set in a variable
data_file5 = "C:\\Users\\taiwo\\OneDrive\\Desktop\\PREWORK_TO\\Module 16\\Project2\\Data Files\\EBOT.csv"
# Use Pandas to read data
data_file_pd5 = pd.read_csv(data_file5)
data_file_pd5.head()

,s/n,country,1990,1991,1992,1993,1994,1995,1996,1997,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,1.0,Belgium,39.7,42.4,43.4,41.8,45.7,47.0,49.6,49.1,...,48.6,54.0,48.6,46.5,48.8,47.5,50.8,48.8,48.4,50.8
1,2.0,Czech Republic,7.6,7.0,7.0,6.8,7.7,8.6,10.4,10.5,...,11.5,11.6,12.6,11.0,12.0,12.7,13.5,13.7,16.2,15.8
2,3.0,France,120.0,126.8,124.5,116.4,113.4,118.1,123.5,122.5,...,133.7,132.4,127.5,126.2,125.8,115.6,117.0,118.3,121.4,116.9
3,4.0,Germany,167.1,181.0,187.9,189.6,193.2,195.4,208.6,209.3,...,197.8,204.1,199.4,199.3,207.2,196.1,198.5,205.0,210.0,198.8
4,5.0,Italy,131.6,130.9,133.4,127.3,126.3,134.4,133.9,133.9,...,141.3,148.5,141.3,132.1,123.2,115.1,121.5,121.3,124.4,120.7

In [16]:
# Save path to data set in a variable
data_file6 = "C:\\Users\\taiwo\\OneDrive\\Desktop\\PREWORK_TO\\Module 16\\Project2\\Data Files\\EIG.csv"
# Use Pandas to read data
data_file_pd6 = pd.read_csv(data_file6)
data_file_pd6.head()

,s/n,country,1990,1991,1992,1993,1994,1995,1996,1997,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,1.0,Belgium,0.144,0.148,0.147,0.145,0.149,0.148,0.154,0.148,...,0.118,0.123,0.113,0.108,0.112,0.105,0.104,0.109,0.105,0.099
1,2.0,Czech Republic,0.220,0.226,0.222,0.215,0.201,0.192,0.190,0.192,...,0.134,0.139,0.132,0.132,0.132,0.125,0.119,0.115,0.115,0.110
2,3.0,France,0.121,0.127,0.123,0.126,0.119,0.121,0.125,0.119,...,0.101,0.102,0.097,0.097,0.096,0.092,0.092,0.089,0.087,0.086
3,4.0,Germany,0.131,0.121,0.117,0.117,0.113,0.112,0.115,0.113,...,0.090,0.091,0.083,0.083,0.084,0.080,0.079,0.078,0.077,0.072
4,5.0,Italy,0.080,0.081,0.080,0.080,0.077,0.079,0.078,0.078,...,0.075,0.076,0.073,0.072,0.071,0.067,0.069,0.067,0.067,0.067

In [17]:
# ====== Connection ====== #
# Connection to Mongo
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Connection to the database
db = client.Project2

# Connection to the collection
collection = db.TotalEnergyConsumption

In [18]:
# Read the row from datafile3 to create a dictionary
for _, row in data_file_pd3.iterrows():
   dic = {
       'country':row["country"],
       '1990': row["1990"],
       '1991': row["1991"],
       '1992': row["1992"],
       '1993': row["1993"],
       '1994': row["1994"],
       '1995': row["1995"],
       '1996': row["1996"],
       '1997': row["1997"],
       '1998': row["1998"],
       '1999': row["1999"],
       '2000': row["2000"],
       '2001': row["2001"],
       '2002': row["2002"],
       '2003': row["2003"],
       '2004': row["2004"],
       '2005': row["2005"],
       '2006': row["2006"],
       '2007': row["2007"],
       '2008': row["2008"],
       '2009': row["2009"],
       '2010': row["2010"],
        '2011': row["2011"],
        '2012': row["2012"],
        '2013': row["2013"],
        '2014': row["2014"],
        '2015': row["2015"],
        '2016': row["2016"],
        '2017': row["2017"],
        '2018': row["2018"]       
       
   }
   #insert dictionary into mongo
   #collection.insert_one(dic)

In [19]:
# ====== Connection ====== #
# Connection to Mongo
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Connection to the database
db = client.Project2

# Connection to the collection
collection = db.TotalEnergyProduction

In [20]:
# Read the row from datafile4 to create a dictionary
for _, row in data_file_pd4.iterrows():
   dic = {
       'country':row["country"],
       '1990': row["1990"],
       '1991': row["1991"],
       '1992': row["1992"],
       '1993': row["1993"],
       '1994': row["1994"],
       '1995': row["1995"],
       '1996': row["1996"],
       '1997': row["1997"],
       '1998': row["1998"],
       '1999': row["1999"],
       '2000': row["2000"],
       '2001': row["2001"],
       '2002': row["2002"],
       '2003': row["2003"],
       '2004': row["2004"],
       '2005': row["2005"],
       '2006': row["2006"],
       '2007': row["2007"],
       '2008': row["2008"],
       '2009': row["2009"],
       '2010': row["2010"],
        '2011': row["2011"],
        '2012': row["2012"],
        '2013': row["2013"],
        '2014': row["2014"],
        '2015': row["2015"],
        '2016': row["2016"],
        '2017': row["2017"],
        '2018': row["2018"]       
       
   }
   #insert dictionary into mongo
   #collection.insert_one(dic)

In [21]:
# ====== Connection ====== #
# Connection to Mongo
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Connection to the database
db = client.Project2

# Connection to the collection
collection = db.EnergyBalanceOfTrade

In [22]:
# Read the row from datafile5 to create a dictionary
for _, row in data_file_pd5.iterrows():
   dic = {
       'country':row["country"],
       '1990': row["1990"],
       '1991': row["1991"],
       '1992': row["1992"],
       '1993': row["1993"],
       '1994': row["1994"],
       '1995': row["1995"],
       '1996': row["1996"],
       '1997': row["1997"],
       '1998': row["1998"],
       '1999': row["1999"],
       '2000': row["2000"],
       '2001': row["2001"],
       '2002': row["2002"],
       '2003': row["2003"],
       '2004': row["2004"],
       '2005': row["2005"],
       '2006': row["2006"],
       '2007': row["2007"],
       '2008': row["2008"],
       '2009': row["2009"],
       '2010': row["2010"],
        '2011': row["2011"],
        '2012': row["2012"],
        '2013': row["2013"],
        '2014': row["2014"],
        '2015': row["2015"],
        '2016': row["2016"],
        '2017': row["2017"],
        '2018': row["2018"]       
       
   }
   #insert dictionary into mongo
   #collection.insert_one(dic)

In [23]:
# ====== Connection ====== #
# Connection to Mongo
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Connection to the database
db = client.Project2

# Connection to the collection
collection = db.EnergyIntensityGDP

In [24]:
# Read the row from datafile6 to create a dictionary
for _, row in data_file_pd6.iterrows():
   dic = {
       'country':row["country"],
       '1990': row["1990"],
       '1991': row["1991"],
       '1992': row["1992"],
       '1993': row["1993"],
       '1994': row["1994"],
       '1995': row["1995"],
       '1996': row["1996"],
       '1997': row["1997"],
       '1998': row["1998"],
       '1999': row["1999"],
       '2000': row["2000"],
       '2001': row["2001"],
       '2002': row["2002"],
       '2003': row["2003"],
       '2004': row["2004"],
       '2005': row["2005"],
       '2006': row["2006"],
       '2007': row["2007"],
       '2008': row["2008"],
       '2009': row["2009"],
       '2010': row["2010"],
        '2011': row["2011"],
        '2012': row["2012"],
        '2013': row["2013"],
        '2014': row["2014"],
        '2015': row["2015"],
        '2016': row["2016"],
        '2017': row["2017"],
        '2018': row["2018"]       
       
   }
   #insert dictionary into mongo
   #collection.insert_one(dic)

In [36]:
# Save path to data set in a variable
data_file7 = "C:\\Users\\taiwo\\OneDrive\\Desktop\\PREWORK_TO\\Module 16\\Project2\\Data Files\\TEC2.csv"

In [37]:
# Use Pandas to read data - TEC2
data_file_pd7 = pd.read_csv(data_file7)
data_file_pd7.head()

,Year,Belgium,Czech Republic,France,Germany,Italy,Netherlands,Poland,Portugal,Romania,...,Australia,New Zealand,Algeria,Egypt,Nigeria,South Africa,Iran,Kuwait,Saudi Arabia,United Arab Emirates
0,1990,48,50,225,355,151,67,104,17,62,...,87,14,22,32,66,90,69,9,58,20
1,1991,50,45,237,344,155,69,101,17,51,...,86,14,23,32,70,93,77,3,68,23
2,1992,51,44,234,338,154,69,99,19,47,...,87,14,24,33,72,88,81,9,77,22
3,1993,49,43,238,335,153,70,101,18,46,...,91,15,24,34,74,94,87,12,80,24
4,1994,52,41,231,333,151,71,97,19,43,...,92,15,23,33,72,98,97,14,84,26

In [38]:
from pandas import *
import seaborn as sns
from IPython.display import HTML
#convert dataframe to HTML
html_table = data_file_pd7.to_html()
html_table

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Year</th>\n      <th>Belgium</th>\n      <th>Czech Republic</th>\n      <th>France</th>\n      <th>Germany</th>\n      <th>Italy</th>\n      <th>Netherlands</th>\n      <th>Poland</th>\n      <th>Portugal</th>\n      <th>Romania</th>\n      <th>Spain</th>\n      <th>Sweden</th>\n      <th>United Kingdom</th>\n      <th>Norway</th>\n      <th>Turkey</th>\n      <th>Kazakhstan</th>\n      <th>Russia</th>\n      <th>Ukraine</th>\n      <th>Uzbekistan</th>\n      <th>Canada</th>\n      <th>United States</th>\n      <th>Argentina</th>\n      <th>Brazil</th>\n      <th>Chile</th>\n      <th>Colombia</th>\n      <th>Mexico</th>\n      <th>Venezuela</th>\n      <th>China</th>\n      <th>India</th>\n      <th>Indonesia</th>\n      <th>Japan</th>\n      <th>Malaysia</th>\n      <th>South Korea</th>\n      <th>Taiwan</th>\n      <th>Thailand</th>\n      <th>Australia</th>\n      <th>New Zealand</th>\n      <th>Algeria</th>\n      <th>Egypt</th>\n      <th>Nigeria</th>\n      <th>South Africa</th>\n      <th>Iran</th>\n      <th>Kuwait</th>\n      <th>Saudi Arabia</th>\n      <th>United Arab Emirates</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1990</td>\n      <td>48</td>\n      <td>50</td>\n      <td>225</td>\n      <td>355</td>\n      <td>151</td>\n      <td>67</td>\n      <td>104</td>\n      <td>17</td>\n      <td>62</td>\n      <td>91</td>\n      <td>46</td>\n      <td>206</td>\n      <td>21</td>\n      <td>52</td>\n      <td>73</td>\n      <td>882</td>\n      <td>243</td>\n      <td>46</td>\n      <td>211</td>\n      <td>1910</td>\n      <td>46</td>\n      <td>141</td>\n      <td>14</td>\n      <td>24</td>\n      <td>123</td>\n      <td>40</td>\n      <td>874</td>\n      <td>306</td>\n      <td>99</td>\n      <td>440</td>\n      <td>22</td>\n      <td>94</td>\n      <td>48</td>\n      <td>42</td>\n      <td>87</td>\n      <td>14</td>\n      <td>22</td>\n      <td>32</td>\n      <td>66</td>\n      <td>90</td>\n      <td>69</td>\n      <td>9</td>\n      <td>58</td>\n      <td>20</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1991</td>\n      <td>50</td>\n      <td>45</td>\n      <td>237</td>\n      <td>344</td>\n      <td>155</td>\n      <td>69</td>\n      <td>101</td>\n      <td>17</td>\n      <td>51</td>\n      <td>94</td>\n      <td>48</td>\n      <td>213</td>\n      <td>22</td>\n      <td>52</td>\n      <td>75</td>\n      <td>872</td>\n      <td>244</td>\n      <td>48</td>\n      <td>210</td>\n      <td>1925</td>\n      <td>47</td>\n      <td>143</td>\n      <td>14</td>\n      <td>24</td>\n      <td>129</td>\n      <td>41</td>\n      <td>848</td>\n      <td>318</td>\n      <td>103</td>\n      <td>445</td>\n      <td>27</td>\n      <td>101</td>\n      <td>52</td>\n      <td>46</td>\n      <td>86</td>\n      <td>14</td>\n      <td>23</td>\n      <td>32</td>\n      <td>70</td>\n      <td>93</td>\n      <td>77</td>\n      <td>3</td>\n      <td>68</td>\n      <td>23</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1992</td>\n      <td>51</td>\n      <td>44</td>\n      <td>234</td>\n      <td>338</td>\n      <td>154</td>\n      <td>69</td>\n      <td>99</td>\n      <td>19</td>\n      <td>47</td>\n      <td>95</td>\n      <td>46</td>\n      <td>212</td>\n      <td>22</td>\n      <td>53</td>\n      <td>79</td>\n      <td>800</td>\n      <td>212</td>\n      <td>45</td>\n      <td>215</td>\n      <td>1964</td>\n      <td>50</td>\n      <td>145</td>\n      <td>15</td>\n      <td>25</td>\n      <td>131</td>\n      <td>46</td>\n      <td>877</td>\n      <td>330</td>\n      <td>108</td>\n      <td>455</td>\n      <td>30</td>\n      <td>111</td>\n      <td>54</td>\n      <td>49</td>\n      <td>87</td>\n      <td>14</td>\n      <td>24</td>\n      <td>33</td>\n      <td>72</td>\n      <td>88</td>\n      <td>81</td>\n      <td>9</td>\n      <td>77</td>\n      <td>22</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1993</td>\n      <td>49</td>\n      <td>43</td>\n      <td>238</td>\n      <td>335</td>\n      <td>153</td>\n      <td>70</td>\n      <td>101</td>\n      <td>18</td>\n      <td>46</td>\n      <td>92</td>\n      <td>46</td>\n      <td>214</td>\n      <td>24</td>\n      <td>57</td>\n      <td>66</td>\n      <td>756</td>\n      <td>189</td>\n      <td>47</td>\n      <td>223</td>\n      <td>1998</td>\n      <td>50</td>\n      <td>148</td>\n      <td>16</td>\n      <td>26</td>\n      <td>133</td>\n      <td>43</td>\n      <td>929</td>\n      <td>338</td>\n      <td>119</td>\n      <td>457</td>\n      <td>32</td>\n      <td>125</td>\n      <td>58</td>\n      <td>51</td>\n      <td>91</td>\n      <td>15</td>\n      <td>24</td>\n      <td>34</td>\n      <td>74</td>\n      <td>94</td>\n      <td>87</td>\n      <td>12</td>\n      <td>80</td>\n      <td>24</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1994</td>\n      <td>52</td>\n      <td>41</td>\n      <td>231</td>\n      <td>333</td>\n      <td>151</td>\n      <td>71</td>\n      <td>97</td>\n      <td>19</td>\n      <td>43</td>\n      <td>96</td>\n      <td>49</td>\n      <td>221</td>\n      <td>23</td>\n      <td>56</td>\n      <td>58</td>\n      <td>659</td>\n      <td>161</td>\n      <td>47</td>\n      <td>231</td>\n      <td>2036</td>\n      <td>53</td>\n      <td>156</td>\n      <td>17</td>\n      <td>27</td>\n      <td>136</td>\n      <td>50</td>\n      <td>973</td>\n      <td>351</td>\n      <td>119</td>\n      <td>483</td>\n      <td>32</td>\n      <td>133</td>\n      <td>60</td>\n      <td>57</td>\n      <td>92</td>\n      <td>15</td>\n      <td>23</td>\n      <td>33</td>\n      <td>72</td>\n      <td>98</td>\n      <td>97</td>\n      <td>14</td>\n      <td>84</td>\n      <td>26</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>1995</td>\n      <td>53</td>\n      <td>42</td>\n      <td>240</td>\n      <td>336</td>\n      <td>159</td>\n      <td>74</td>\n      <td>100</td>\n      <td>20</td>\n      <td>47</td>\n      <td>101</td>\n      <td>49</td>\n      <td>217</td>\n      <td>23</td>\n      <td>62</td>\n      <td>52</td>\n      <td>639</td>\n      <td>160</td>\n      <td>43</td>\n      <td>234</td>\n      <td>2063</td>\n      <td>54</td>\n      <td>161</td>\n      <td>18</td>\n      <td>28</td>\n      <td>132</td>\n      <td>47</td>\n      <td>1045</td>\n      <td>371</td>\n      <td>131</td>\n      <td>495</td>\n      <td>35</td>\n      <td>146</td>\n      <td>64</td>\n      <td>62</td>\n      <td>94</td>\n      <td>15</td>\n      <td>24</td>\n      <td>35</td>\n      <td>73</td>\n      <td>104</td>\n      <td>101</td>\n      <td>15</td>\n      <td>85</td>\n      <td>28</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>1996</td>\n      <td>56</td>\n      <td>43</td>\n      <td>250</td>\n      <td>348</td>\n      <td>159</td>\n      <td>77</td>\n      <td>107</td>\n      <td>20</td>\n      <td>48</td>\n      <td>99</td>\n      <td>50</td>\n      <td>226</td>\n      <td>23</td>\n      <td>67</td>\n      <td>45</td>\n      <td>634</td>\n      <td>147</td>\n      <td>44</td>\n      <td>238</td>\n      <td>2108</td>\n      <td>56</td>\n      <td>170</td>\n      <td>20</td>\n      <td>28</td>\n      <td>135</td>\n      <td>50</td>\n      <td>1074</td>\n      <td>383</td>\n      <td>136</td>\n      <td>506</td>\n      <td>39</td>\n      <td>158</td>\n      <td>67</td>\n      <td>69</td>\n      <td>100</td>\n      <td>16</td>\n      <td>23</td>\n      <td>37</td>\n      <td>76</td>\n      <td>107</td>\n      <td>98</td>\n      <td>15</td>\n      <td>90</td>\n      <td>29</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>1997</td>\n      <td>56</td>\n      <td>43</td>\n      <td>244</td>\n      <td>346</td>\n      <td>162</td>\n      <td>75</td>\n      <td>102</td>\n      <td>21</td>\n      <td>45</td>\n      <td>105</td>\n      <td>49</td>\n      <td>219</td>\n      <td>24</td>\n      <td>70</td>\n      <td>40</td>\n      <td>606</td>\n      <td>140</td>\n      <td>45</td>\n      <td>241</td>\n      <td>2130</td>\n      <td>58</td>\n      <td>179</td>\n      <td>23</td>\n      <td>27</td>\n      <td>142</td>\n      <td>50</td>\n      <td>1073</td>\n      <td>398</td>\n      <td>140</td>\n      <td>511</td>\n      <td>45</td>\n      <td>172</td>\n      <td>71</td>\n      <td>71</td>\n      <td>101</td>\n      <td>16</td>\n      <td>24</td>\n      <td>39</td>\n      <td>79</td>\n      <td>109</td>\n      <td>109</td>\n      <td>15</td>\n      <td>86</td>\n      <td>31</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>1998</td>\n      <td>57</td>\n      <td>42</td>\n      <td>251</td>\n      <td>343</td>\n      <td>166</td>\n      <td>76</td>\n      <td>95</td>\n      <td>23</td>\n      <td>41</td>\n      <td>111</td>\n      <td>50</td>\n      <td>221</td>\n      <td>25</td>\n      <td>72</td>\n      <td>39</td>\n      <td>591</td>\n      <td>132</td>\n      <td>50</td>\n      <td>240</td>\n      <td>2156</td>\n      <td>60</td>\n      <td>183</td>\n      <td>24</td>\n      <td>29</td>\n      <td>145</td>\n      <td>52</td>\n      <td>1078</td>\n      <td>407</td>\n      <td>137</td>\n      <td>501</td>\n      <td>42</td>\n      <td>158</td>\n      <td>75</td>\n      <td>66</td>\n      <td>104</td>\n      <td>16</td>\n      <td>25</td>\n      <td>42</td>\n      <td>80</td>\n      <td>111</td>\n      <td>111</td>\n      <td>17</td>\n      <td>92</td>\n      <td>32</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>1999</td>\n      <td>57</td>\n      <td>39</td>\n      <td>252</td>\n      <td>335</td>\n      <td>169</td>\n      <td>75</td>\n      <td>93</td>\n      <td>24</td>\n      <td>36</td>\n      <td>116</td>\n      <td>49</td>\n      <td>222</td>\n      <td>26</td>\n      <td>70</td>\n      <td>36</td>\n      <td>608</td>\n      <td>131</td>\n      <td>51</td>\n      <td>246</td>\n      <td>2206</td>\n      <td>61</td>\n      <td>187</td>\n      <td>25</td>\n      <td>26</td>\n      <td>150</td>\n      <td>50</td>\n      <td>1099</td>\n      <td>431</td>\n      <td>144</td>\n      <td>509</td>\n      <td>43</td>\n      <td>174</td>\n      <td>79</td>\n      <td>71</td>\n      <td>106</td>\n      <td>17</td>\n      <td>27</td>\n      <td>42</td>\n      <td>83</td>\n      <td>109</td>\n      <td>126</td>\n      <td>18</td>\n      <td>94</td>\n      <td>32</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>2000</td>\n      <td>58</td>\n      <td>41</td>\n      <td>255</td>\n      <td>337</td>\n      <td>172</td>\n      <td>76</td>\n      <td>89</td>\n      <td>25</td>\n      <td>36</td>\n      <td>122</td>\n      <td>46</td>\n      <td>223</td>\n      <td>26</td>\n      <td>76</td>\n      <td>36</td>\n      <td>619</td>\n      <td>129</td>\n      <td>51</td>\n      <td>254</td>\n      <td>2269</td>\n      <td>62</td>\n      <td>188</td>\n      <td>25</td>\n      <td>26</td>\n      <td>150</td>\n      <td>51</td>\n      <td>1130</td>\n      <td>441</td>\n      <td>156</td>\n      <td>519</td>\n      <td>49</td>\n      <td>190</td>\n      <td>85</td>\n      <td>72</td>\n      <td>108</td>\n      <td>17</td>\n      <td>27</td>\n      <td>40</td>\n      <td>87</td>\n      <td>111</td>\n      <td>123</td>\n      <td>19</td>\n      <td>98</td>\n      <td>32</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>2001</td>\n      <td>58</td>\n      <td>42</td>\n      <td>260</td>\n      <td>346</td>\n      <td>172</td>\n      <td>78</td>\n      <td>90</td>\n      <td>25</td>\n      <td>37</td>\n      <td>125</td>\n      <td>49</td>\n      <td>224</td>\n      <td>27</td>\n      <td>70</td>\n      <td>35</td>\n      <td>625</td>\n      <td>130</td>\n      <td>51</td>\n      <td>250</td>\n      <td>2226</td>\n      <td>59</td>\n      <td>191</td>\n      <td>25</td>\n      <td>26</td>\n      <td>155</td>\n      <td>53</td>\n      <td>1168</td>\n      <td>448</td>\n      <td>159</td>\n      <td>511</td>\n      <td>51</td>\n      <td>193</td>\n      <td>89</td>\n      <td>74</td>\n      <td>106</td>\n      <td>17</td>\n      <td>27</td>\n      <td>46</td>\n      <td>91</td>\n      <td>107</td>\n      <td>133</td>\n      <td>20</td>\n      <td>100</td>\n      <td>40</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>2002</td>\n      <td>56</td>\n      <td>43</td>\n      <td>261</td>\n      <td>339</td>\n      <td>173</td>\n      <td>78</td>\n      <td>89</td>\n      <td>26</td>\n      <td>38</td>\n      <td>129</td>\n      <td>52</td>\n      <td>220</td>\n      <td>25</td>\n      <td>74</td>\n      <td>40</td>\n      <td>622</td>\n      <td>131</td>\n      <td>53</td>\n      <td>251</td>\n      <td>2256</td>\n      <td>57</td>\n      <td>196</td>\n      <td>26</td>\n      <td>25</td>\n      <td>155</td>\n      <td>57</td>\n      <td>1246</td>\n      <td>462</td>\n      <td>165</td>\n      <td>512</td>\n      <td>53</td>\n      <td>201</td>\n      <td>93</td>\n      <td>82</td>\n      <td>109</td>\n      <td>17</td>\n      <td>29</td>\n      <td>47</td>\n      <td>94</td>\n      <td>103</td>\n      <td>138</td>\n      <td>21</td>\n      <td>111</td>\n      <td>40</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>2003</td>\n      <td>58</td>\n      <td>45</td>\n      <td>267</td>\n      <td>337</td>\n      <td>182</td>\n      <td>81</td>\n      <td>91</td>\n      <td>25</td>\n      <td>40</td>\n      <td>133</td>\n      <td>51</td>\n      <td>224</td>\n      <td>27</td>\n      <td>78</td>\n      <td>43</td>\n      <td>645</td>\n      <td>137</td>\n      <td>52</td>\n      <td>264</td>\n      <td>2261</td>\n      <td>61</td>\n      <td>199</td>\n      <td>26</td>\n      <td>26</td>\n      <td>165</td>\n      <td>53</td>\n      <td>1420</td>\n      <td>474</td>\n      <td>165</td>\n      <td>509</td>\n      <td>57</td>\n      <td>206</td>\n      <td>97</td>\n      <td>89</td>\n      <td>110</td>\n      <td>17</td>\n      <td>31</td>\n      <td>49</td>\n      <td>98</td>\n      <td>116</td>\n      <td>143</td>\n      <td>22</td>\n      <td>113</td>\n      <td>39</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>2004</td>\n      <td>58</td>\n      <td>46</td>\n      <td>271</td>\n      <td>339</td>\n      <td>183</td>\n      <td>82</td>\n      <td>91</td>\n      <td>26</td>\n      <td>39</td>\n      <td>140</td>\n      <td>53</td>\n      <td>222</td>\n      <td>27</td>\n      <td>81</td>\n      <td>51</td>\n      <td>647</td>\n      <td>138</td>\n      <td>51</td>\n      <td>270</td>\n      <td>2308</td>\n      <td>67</td>\n      <td>210</td>\n      <td>28</td>\n      <td>26</td>\n      <td>167</td>\n      <td>56</td>\n      <td>1615</td>\n      <td>499</td>\n      <td>176</td>\n      <td>524</td>\n      <td>61</td>\n      <td>212</td>\n      <td>100</td>\n      <td>96</td>\n      <td>112</td>\n      <td>18</td>\n      <td>31</td>\n      <td>53</td>\n      <td>99</td>\n      <td>126</td>\n      <td>156</td>\n      <td>23</td>\n      <td>120</td>\n      <td>42</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>2005</td>\n      <td>58</td>\n      <td>45</td>\n      <td>272</td>\n      <td>337</td>\n      <td>186</td>\n      <td>81</td>\n      <td>92</td>\n      <td>26</td>\n      <td>39</td>\n      <td>143</td>\n      <td>52</td>\n      <td>223</td>\n      <td>27</td>\n      <td>84</td>\n      <td>51</td>\n      <td>651</td>\n      <td>141</td>\n      <td>47</td>\n      <td>273</td>\n      <td>2319</td>\n      <td>67</td>\n      <td>216</td>\n      <td>28</td>\n      <td>27</td>\n      <td>178</td>\n      <td>55</td>\n      <td>1782</td>\n      <td>514</td>\n      <td>179</td>\n      <td>523</td>\n      <td>67</td>\n      <td>214</td>\n      <td>102</td>\n      <td>99</td>\n      <td>113</td>\n      <td>17</td>\n      <td>32</td>\n      <td>62</td>\n      <td>105</td>\n      <td>122</td>\n      <td>173</td>\n      <td>26</td>\n      <td>123</td>\n      <td>45</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>2006</td>\n      <td>58</td>\n      <td>46</td>\n      <td>268</td>\n      <td>346</td>\n      <td>184</td>\n      <td>80</td>\n      <td>97</td>\n      <td>25</td>\n      <td>40</td>\n      <td>142</td>\n      <td>50</td>\n      <td>219</td>\n      <td>27</td>\n      <td>93</td>\n      <td>61</td>\n      <td>670</td>\n      <td>137</td>\n      <td>48</td>\n      <td>278</td>\n      <td>2297</td>\n      <td>73</td>\n      <td>223</td>\n      <td>30</td>\n      <td>28</td>\n      <td>182</td>\n      <td>62</td>\n      <td>1950</td>\n      <td>533</td>\n      <td>183</td>\n      <td>523</td>\n      <td>67</td>\n      <td>218</td>\n      <td>105</td>\n      <td>101</td>\n      <td>118</td>\n      <td>17</td>\n      <td>35</td>\n      <td>65</td>\n      <td>106</td>\n      <td>126</td>\n      <td>180</td>\n      <td>26</td>\n      <td>136</td>\n      <td>46</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>2007</td>\n      <td>57</td>\n      <td>46</td>\n      <td>265</td>\n      <td>328</td>\n      <td>184</td>\n      <td>80</td>\n      <td>96</td>\n      <td>25</td>\n      <td>40</td>\n      <td>144</td>\n      <td>50</td>\n      <td>211</td>\n      <td>28</td>\n      <td>100</td>\n      <td>66</td>\n      <td>672</td>\n      <td>138</td>\n      <td>48</td>\n      <td>277</td>\n      <td>2338</td>\n      <td>74</td>\n      <td>236</td>\n      <td>31</td>\n      <td>28</td>\n      <td>181</td>\n      <td>58</td>\n      <td>2099</td>\n      <td>568</td>\n      <td>183</td>\n      <td>518</td>\n      <td>73</td>\n      <td>227</td>\n      <td>110</td>\n      <td>105</td>\n      <td>122</td>\n      <td>17</td>\n      <td>37</td>\n      <td>69</td>\n      <td>110</td>\n      <td>135</td>\n      <td>191</td>\n      <td>26</td>\n      <td>140</td>\n      <td>50</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>2008</td>\n      <td>58</td>\n      <td>45</td>\n      <td>267</td>\n      <td>331</td>\n      <td>182</td>\n      <td>79</td>\n      <td>98</td>\n      <td>25</td>\n      <td>40</td>\n      <td>139</td>\n      <td>50</td>\n      <td>208</td>\n      <td>32</td>\n      <td>99</td>\n      <td>70</td>\n      <td>687</td>\n      <td>135</td>\n      <td>50</td>\n      <td>273</td>\n      <td>2278</td>\n      <td>78</td>\n      <td>249</td>\n      <td>30</td>\n      <td>30</td>\n      <td>180</td>\n      <td>65</td>\n      <td>2155</td>\n      <td>600</td>\n      <td>186</td>\n      <td>498</td>\n      <td>77</td>\n      <td>232</td>\n      <td>106</td>\n      <td>108</td>\n      <td>127</td>\n      <td>18</td>\n      <td>37</td>\n      <td>72</td>\n      <td>113</td>\n      <td>145</td>\n      <td>205</td>\n      <td>29</td>\n      <td>157</td>\n      <td>60</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>2009</td>\n      <td>56</td>\n      <td>43</td>\n      <td>255</td>\n      <td>310</td>\n      <td>170</td>\n      <td>78</td>\n      <td>94</td>\n      <td>24</td>\n      <td>35</td>\n      <td>128</td>\n      <td>45</td>\n      <td>196</td>\n      <td>32</td>\n      <td>99</td>\n      <td>63</td>\n      <td>646</td>\n      <td>114</td>\n      <td>44</td>\n      <td>261</td>\n      <td>2165</td>\n      <td>76</td>\n      <td>241</td>\n      <td>30</td>\n      <td>31</td>\n      <td>180</td>\n      <td>65</td>\n      <td>2297</td>\n      <td>666</td>\n      <td>199</td>\n      <td>475</td>\n      <td>73</td>\n      <td>234</td>\n      <td>103</td>\n      <td>108</td>\n      <td>127</td>\n      <td>18</td>\n      <td>41</td>\n      <td>74</td>\n      <td>111</td>\n      <td>147</td>\n      <td>204</td>\n      <td>31</td>\n      <td>167</td>\n      <td>64</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>2010</td>\n      <td>60</td>\n      <td>45</td>\n      <td>263</td>\n      <td>326</td>\n      <td>174</td>\n      <td>84</td>\n      <td>101</td>\n      <td>23</td>\n      <td>35</td>\n      <td>128</td>\n      <td>51</td>\n      <td>203</td>\n      <td>30</td>\n      <td>106</td>\n      <td>69</td>\n      <td>688</td>\n      <td>132</td>\n      <td>

In [ ]:
# Display a statistical overview of the DataFrame
data_file_pd7.describe()

In [ ]:
data_file_pd7["Year"].head()

In [ ]:
data_file_pd6["country"].head()

In [ ]:
data_file_pd7.dtypes

In [ ]:
data_file_pd7 = data_file_pd7.astype(float)

In [ ]:
data_file_pd7["Belgium"].dtypes

In [ ]:
# ====== Connection ====== #
# Connection to Mongo
conn = 'mongodb://localhost:27017'
client = pymongo.MongoClient(conn)

# Connection to the database
db = client.Project2

# Connection to the collection
collection = db.TEC2

In [ ]:
# Read the row from datafile7 to create a dictionary
for _, row in data_file_pd7.iterrows():
   dic = {
       'Year':row["Year"],
       'Belgium': row["Belgium"], 
       'Czech Republic': row["Czech Republic"],
       'France': row["France"],
       'Germany': row["Germany"],
       'Italy': row["Italy"],
       'Netherlands': row["Netherlands"], 
       'Poland': row["Poland"],
       'Portugal': row["Portugal"],   
       'Romania': row["Romania"],
       'Spain': row["Spain"],
       'Sweden': row["Sweden"],
       'United Kingdom': row["United Kingdom"],
       'Norway': row["Norway"],
       'Turkey': row["Turkey"],
       'Kazakhstan': row["Kazakhstan"],
       'Russia': row["Russia"],
       'Ukraine': row["Ukraine"],
       'Uzbekistan': row["Uzbekistan"],
       'Canada': row["Canada"],
       'United States': row["United States"],
       'Argentina': row["Argentina"],
        'Brazil': row["Brazil"],
        'Chile': row["Chile"],
        'Colombia': row["Colombia"],
        'Mexico': row["Mexico"],
        'Venezuela': row["Venezuela"],
        'China': row["China"],
        'India': row["India"],
        'Indonesia': row["Indonesia"],      
        'Japan': row["Japan"],
       'Malaysia': row["Malaysia"],
       'South Korea': row["South Korea"],
       'Taiwan': row["Taiwan"],
       'Thailand': row["Thailand"],
        'Australia': row["Australia"],
        'New Zealand': row["New Zealand"],
        'Algeria': row["Algeria"],
        'Egypt': row["Egypt"],
        'Nigeria': row["Nigeria"],
        'South Africa': row["South Africa"],
        'Iran': row["Iran"],
        'Kuwait': row["Kuwait"],
        'Saudi Arabia': row["Saudi Arabia"],
        'United Arab Emirates': row["United Arab Emirates"]  
       
   }


   #insert dictionary into mongo
   #collection.insert_one(dic)

In [40]:
# Save path to data set in a variable
data_file8 = "C:\\Users\\taiwo\\OneDrive\\Desktop\\PREWORK_TO\\Module 16\\Project2\\Data Files\\TEP2.csv"

In [41]:
# Use Pandas to read data
data_file_pd8 = pd.read_csv(data_file8)
data_file_pd8.head()

,Year,Belgium,Czech Republic,France,Germany,Italy,Netherlands,Poland,Portugal,Romania,...,Australia,New Zealand,Algeria,Egypt,Nigeria,South Africa,Iran,Kuwait,Saudi Arabia,United Arab Emirates
0,1990,13,41,112,190,26,61,104,3,41,...,157,12,100,55,146,115,188,50,368,110
1,1991,13,39,119,169,26,68,100,3,36,...,167,13,103,56,152,117,200,10,464,127
2,1992,13,37,120,164,28,68,98,3,34,...,171,13,104,57,158,115,215,60,477,134
3,1993,12,36,126,153,29,69,97,3,33,...,174,14,105,60,160,123,228,107,472,131
4,1994,12,34,124,145,30,67,98,3,32,...,173,13,101,59,162,128,231,114,462,134

In [42]:
#convert dataframe to HTML- TEP2
html_table = data_file_pd8.to_html()
html_table

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Year</th>\n      <th>Belgium</th>\n      <th>Czech Republic</th>\n      <th>France</th>\n      <th>Germany</th>\n      <th>Italy</th>\n      <th>Netherlands</th>\n      <th>Poland</th>\n      <th>Portugal</th>\n      <th>Romania</th>\n      <th>Spain</th>\n      <th>Sweden</th>\n      <th>United Kingdom</th>\n      <th>Norway</th>\n      <th>Turkey</th>\n      <th>Kazakhstan</th>\n      <th>Russia</th>\n      <th>Ukraine</th>\n      <th>Uzbekistan</th>\n      <th>Canada</th>\n      <th>United States</th>\n      <th>Argentina</th>\n      <th>Brazil</th>\n      <th>Chile</th>\n      <th>Colombia</th>\n      <th>Mexico</th>\n      <th>Venezuela</th>\n      <th>China</th>\n      <th>India</th>\n      <th>Indonesia</th>\n      <th>Japan</th>\n      <th>Malaysia</th>\n      <th>South Korea</th>\n      <th>Taiwan</th>\n      <th>Thailand</th>\n      <th>Australia</th>\n      <th>New Zealand</th>\n      <th>Algeria</th>\n      <th>Egypt</th>\n      <th>Nigeria</th>\n      <th>South Africa</th>\n      <th>Iran</th>\n      <th>Kuwait</th>\n      <th>Saudi Arabia</th>\n      <th>United Arab Emirates</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1990</td>\n      <td>13</td>\n      <td>41</td>\n      <td>112</td>\n      <td>190</td>\n      <td>26</td>\n      <td>61</td>\n      <td>104</td>\n      <td>3</td>\n      <td>41</td>\n      <td>35</td>\n      <td>30</td>\n      <td>208</td>\n      <td>119</td>\n      <td>26</td>\n      <td>91</td>\n      <td>1296</td>\n      <td>127</td>\n      <td>39</td>\n      <td>276</td>\n      <td>1647</td>\n      <td>48</td>\n      <td>104</td>\n      <td>8</td>\n      <td>48</td>\n      <td>195</td>\n      <td>145</td>\n      <td>881</td>\n      <td>280</td>\n      <td>169</td>\n      <td>76</td>\n      <td>48</td>\n      <td>24</td>\n      <td>11</td>\n      <td>27</td>\n      <td>157</td>\n      <td>12</td>\n      <td>100</td>\n      <td>55</td>\n      <td>146</td>\n      <td>115</td>\n      <td>188</td>\n      <td>50</td>\n      <td>368</td>\n      <td>110</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1991</td>\n      <td>13</td>\n      <td>39</td>\n      <td>119</td>\n      <td>169</td>\n      <td>26</td>\n      <td>68</td>\n      <td>100</td>\n      <td>3</td>\n      <td>36</td>\n      <td>35</td>\n      <td>31</td>\n      <td>215</td>\n      <td>131</td>\n      <td>26</td>\n      <td>92</td>\n      <td>1220</td>\n      <td>111</td>\n      <td>40</td>\n      <td>287</td>\n      <td>1637</td>\n      <td>50</td>\n      <td>105</td>\n      <td>8</td>\n      <td>46</td>\n      <td>204</td>\n      <td>160</td>\n      <td>887</td>\n      <td>290</td>\n      <td>183</td>\n      <td>80</td>\n      <td>53</td>\n      <td>23</td>\n      <td>11</td>\n      <td>30</td>\n      <td>167</td>\n      <td>13</td>\n      <td>103</td>\n      <td>56</td>\n      <td>152</td>\n      <td>117</td>\n      <td>200</td>\n      <td>10</td>\n      <td>464</td>\n      <td>127</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1992</td>\n      <td>13</td>\n      <td>37</td>\n      <td>120</td>\n      <td>164</td>\n      <td>28</td>\n      <td>68</td>\n      <td>98</td>\n      <td>3</td>\n      <td>34</td>\n      <td>34</td>\n      <td>29</td>\n      <td>215</td>\n      <td>147</td>\n      <td>26</td>\n      <td>90</td>\n      <td>1143</td>\n      <td>104</td>\n      <td>41</td>\n      <td>296</td>\n      <td>1642</td>\n      <td>54</td>\n      <td>105</td>\n      <td>9</td>\n      <td>48</td>\n      <td>203</td>\n      <td>162</td>\n      <td>904</td>\n      <td>294</td>\n      <td>187</td>\n      <td>81</td>\n      <td>54</td>\n      <td>21</td>\n      <td>10</td>\n      <td>31</td>\n      <td>171</td>\n      <td>13</td>\n      <td>104</td>\n      <td>57</td>\n      <td>158</td>\n      <td>115</td>\n      <td>215</td>\n      <td>60</td>\n      <td>477</td>\n      <td>134</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1993</td>\n      <td>12</td>\n      <td>36</td>\n      <td>126</td>\n      <td>153</td>\n      <td>29</td>\n      <td>69</td>\n      <td>97</td>\n      <td>3</td>\n      <td>33</td>\n      <td>33</td>\n      <td>29</td>\n      <td>223</td>\n      <td>155</td>\n      <td>26</td>\n      <td>79</td>\n      <td>1063</td>\n      <td>95</td>\n      <td>43</td>\n      <td>318</td>\n      <td>1592</td>\n      <td>57</td>\n      <td>106</td>\n      <td>8</td>\n      <td>49</td>\n      <td>206</td>\n      <td>171</td>\n      <td>933</td>\n      <td>298</td>\n      <td>194</td>\n      <td>89</td>\n      <td>56</td>\n      <td>21</td>\n      <td>10</td>\n      <td>30</td>\n      <td>174</td>\n      <td>14</td>\n      <td>105</td>\n      <td>60</td>\n      <td>160</td>\n      <td>123</td>\n      <td>228</td>\n      <td>107</td>\n      <td>472</td>\n      <td>131</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1994</td>\n      <td>12</td>\n      <td>34</td>\n      <td>124</td>\n      <td>145</td>\n      <td>30</td>\n      <td>67</td>\n      <td>98</td>\n      <td>3</td>\n      <td>32</td>\n      <td>32</td>\n      <td>31</td>\n      <td>252</td>\n      <td>171</td>\n      <td>26</td>\n      <td>71</td>\n      <td>994</td>\n      <td>83</td>\n      <td>46</td>\n      <td>341</td>\n      <td>1652</td>\n      <td>62</td>\n      <td>111</td>\n      <td>8</td>\n      <td>50</td>\n      <td>205</td>\n      <td>178</td>\n      <td>986</td>\n      <td>308</td>\n      <td>208</td>\n      <td>91</td>\n      <td>58</td>\n      <td>20</td>\n      <td>11</td>\n      <td>32</td>\n      <td>173</td>\n      <td>13</td>\n      <td>101</td>\n      <td>59</td>\n      <td>162</td>\n      <td>128</td>\n      <td>231</td>\n      <td>114</td>\n      <td>462</td>\n      <td>134</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>1995</td>\n      <td>12</td>\n      <td>33</td>\n      <td>128</td>\n      <td>145</td>\n      <td>30</td>\n      <td>67</td>\n      <td>100</td>\n      <td>3</td>\n      <td>32</td>\n      <td>32</td>\n      <td>32</td>\n      <td>258</td>\n      <td>185</td>\n      <td>26</td>\n      <td>64</td>\n      <td>970</td>\n      <td>78</td>\n      <td>49</td>\n      <td>352</td>\n      <td>1655</td>\n      <td>67</td>\n      <td>112</td>\n      <td>8</td>\n      <td>59</td>\n      <td>204</td>\n      <td>192</td>\n      <td>1065</td>\n      <td>323</td>\n      <td>215</td>\n      <td>100</td>\n      <td>64</td>\n      <td>22</td>\n      <td>11</td>\n      <td>33</td>\n      <td>187</td>\n      <td>13</td>\n      <td>107</td>\n      <td>60</td>\n      <td>165</td>\n      <td>135</td>\n      <td>238</td>\n      <td>115</td>\n      <td>464</td>\n      <td>137</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>1996</td>\n      <td>12</td>\n      <td>33</td>\n      <td>132</td>\n      <td>143</td>\n      <td>31</td>\n      <td>75</td>\n      <td>102</td>\n      <td>4</td>\n      <td>33</td>\n      <td>33</td>\n      <td>32</td>\n      <td>269</td>\n      <td>208</td>\n      <td>27</td>\n      <td>64</td>\n      <td>969</td>\n      <td>71</td>\n      <td>49</td>\n      <td>361</td>\n      <td>1673</td>\n      <td>73</td>\n      <td>119</td>\n      <td>8</td>\n      <td>65</td>\n      <td>214</td>\n      <td>217</td>\n      <td>1091</td>\n      <td>328</td>\n      <td>223</td>\n      <td>102</td>\n      <td>70</td>\n      <td>23</td>\n      <td>11</td>\n      <td>37</td>\n      <td>190</td>\n      <td>14</td>\n      <td>113</td>\n      <td>59</td>\n      <td>177</td>\n      <td>135</td>\n      <td>235</td>\n      <td>115</td>\n      <td>469</td>\n      <td>140</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>1997</td>\n      <td>13</td>\n      <td>34</td>\n      <td>129</td>\n      <td>145</td>\n      <td>31</td>\n      <td>67</td>\n      <td>100</td>\n      <td>4</td>\n      <td>32</td>\n      <td>32</td>\n      <td>32</td>\n      <td>268</td>\n      <td>213</td>\n      <td>28</td>\n      <td>66</td>\n      <td>937</td>\n      <td>71</td>\n      <td>51</td>\n      <td>367</td>\n      <td>1671</td>\n      <td>77</td>\n      <td>127</td>\n      <td>8</td>\n      <td>67</td>\n      <td>226</td>\n      <td>229</td>\n      <td>1081</td>\n      <td>338</td>\n      <td>228</td>\n      <td>107</td>\n      <td>75</td>\n      <td>25</td>\n      <td>11</td>\n      <td>40</td>\n      <td>201</td>\n      <td>15</td>\n      <td>122</td>\n      <td>58</td>\n      <td>189</td>\n      <td>143</td>\n      <td>238</td>\n      <td>115</td>\n      <td>464</td>\n      <td>147</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>1998</td>\n      <td>13</td>\n      <td>32</td>\n      <td>125</td>\n      <td>137</td>\n      <td>31</td>\n      <td>64</td>\n      <td>87</td>\n      <td>4</td>\n      <td>29</td>\n      <td>33</td>\n      <td>34</td>\n      <td>272</td>\n      <td>207</td>\n      <td>29</td>\n      <td>65</td>\n      <td>944</td>\n      <td>71</td>\n      <td>55</td>\n      <td>371</td>\n      <td>1691</td>\n      <td>80</td>\n      <td>134</td>\n      <td>8</td>\n      <td>73</td>\n      <td>226</td>\n      <td>227</td>\n      <td>1079</td>\n      <td>337</td>\n      <td>229</td>\n      <td>109</td>\n      <td>75</td>\n      <td>28</td>\n      <td>11</td>\n      <td>40</td>\n      <td>217</td>\n      <td>14</td>\n      <td>127</td>\n      <td>57</td>\n      <td>185</td>\n      <td>145</td>\n      <td>241</td>\n      <td>117</td>\n      <td>479</td>\n      <td>150</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>1999</td>\n      <td>14</td>\n      <td>29</td>\n      <td>127</td>\n      <td>138</td>\n      <td>29</td>\n      <td>60</td>\n      <td>84</td>\n      <td>3</td>\n      <td>28</td>\n      <td>31</td>\n      <td>33</td>\n      <td>282</td>\n      <td>210</td>\n      <td>28</td>\n      <td>66</td>\n      <td>962</td>\n      <td>72</td>\n      <td>55</td>\n      <td>369</td>\n      <td>1665</td>\n      <td>81</td>\n      <td>142</td>\n      <td>8</td>\n      <td>76</td>\n      <td>225</td>\n      <td>206</td>\n      <td>1074</td>\n      <td>344</td>\n      <td>238</td>\n      <td>105</td>\n      <td>74</td>\n      <td>32</td>\n      <td>12</td>\n      <td>42</td>\n      <td>214</td>\n      <td>14</td>\n      <td>137</td>\n      <td>59</td>\n      <td>183</td>\n      <td>145</td>\n      <td>244</td>\n      <td>108</td>\n      <td>442</td>\n      <td>142</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>2000</td>\n      <td>14</td>\n      <td>31</td>\n      <td>131</td>\n      <td>136</td>\n      <td>28</td>\n      <td>58</td>\n      <td>80</td>\n      <td>4</td>\n      <td>28</td>\n      <td>32</td>\n      <td>30</td>\n      <td>272</td>\n      <td>228</td>\n      <td>26</td>\n      <td>79</td>\n      <td>978</td>\n      <td>72</td>\n      <td>55</td>\n      <td>377</td>\n      <td>1663</td>\n      <td>83</td>\n      <td>148</td>\n      <td>9</td>\n      <td>72</td>\n      <td>228</td>\n      <td>216</td>\n      <td>1124</td>\n      <td>351</td>\n      <td>237</td>\n      <td>106</td>\n      <td>78</td>\n      <td>36</td>\n      <td>12</td>\n      <td>44</td>\n      <td>234</td>\n      <td>14</td>\n      <td>142</td>\n      <td>53</td>\n      <td>198</td>\n      <td>145</td>\n      <td>254</td>\n      <td>114</td>\n      <td>476</td>\n      <td>154</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>2001</td>\n      <td>13</td>\n      <td>32</td>\n      <td>132</td>\n      <td>135</td>\n      <td>27</td>\n      <td>61</td>\n      <td>81</td>\n      <td>4</td>\n      <td>28</td>\n      <td>34</td>\n      <td>34</td>\n      <td>262</td>\n      <td>227</td>\n      <td>25</td>\n      <td>84</td>\n      <td>1008</td>\n      <td>72</td>\n      <td>56</td>\n      <td>381</td>\n      <td>1684</td>\n      <td>85</td>\n      <td>152</td>\n      <td>9</td>\n      <td>72</td>\n      <td>234</td>\n      <td>212</td>\n      <td>1176</td>\n      <td>358</td>\n      <td>242</td>\n      <td>105</td>\n      <td>79</td>\n      <td>37</td>\n      <td>11</td>\n      <td>43</td>\n      <td>249</td>\n      <td>15</td>\n      <td>137</td>\n      <td>57</td>\n      <td>208</td>\n      <td>144</td>\n      <td>248</td>\n      <td>112</td>\n      <td>464</td>\n      <td>155</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>2002</td>\n      <td>13</td>\n      <td>32</td>\n      <td>134</td>\n      <td>134</td>\n      <td>29</td>\n      <td>61</td>\n      <td>80</td>\n      <td>4</td>\n      <td>29</td>\n      <td>32</td>\n      <td>32</td>\n      <td>259</td>\n      <td>236</td>\n      <td>24</td>\n      <td>91</td>\n      <td>1046</td>\n      <td>73</td>\n      <td>56</td>\n      <td>386</td>\n      <td>1656</td>\n      <td>83</td>\n      <td>168</td>\n      <td>9</td>\n      <td>68</td>\n      <td>237</td>\n      <td>203</td>\n      <td>1227</td>\n      <td>368</td>\n      <td>248</td>\n      <td>100</td>\n      <td>82</td>\n      <td>38</td>\n      <td>12</td>\n      <td>46</td>\n      <td>254</td>\n      <td>15</td>\n      <td>143</td>\n      <td>59</td>\n      <td>192</td>\n      <td>143</td>\n      <td>254</td>\n      <td>101</td>\n      <td>435</td>\n      <td>148</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>2003</td>\n      <td>14</td>\n      <td>34</td>\n      <td>136</td>\n      <td>135</td>\n      <td>30</td>\n      <td>59</td>\n      <td>80</td>\n      <td>4</td>\n      <td>29</td>\n      <td>33</td>\n      <td>31</td>\n      <td>247</td>\n      <td>235</td>\n      <td>24</td>\n      <td>102</td>\n      <td>1119</td>\n      <td>72</td>\n      <td>57</td>\n      <td>388</td>\n      <td>1635</td>\n      <td>86</td>\n      <td>178</td>\n      <td>9</td>\n      <td>73</td>\n      <td>251</td>\n      <td>179</td>\n      <td>1375</td>\n      <td>381</td>\n      <td>255</td>\n      <td>87</td>\n      <td>85</td>\n      <td>41</td>\n      <td>12</td>\n      <td>49</td>\n      <td>252</td>\n      <td>13</td>\n      <td>155</td>\n      <td>62</td>\n      <td>216</td>\n      <td>152</td>\n      <td>281</td>\n      <td>121</td>\n      <td>506</td>\n      <td>162</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>2004</td>\n      <td>14</td>\n      <td>35</td>\n      <td>137</td>\n      <td>137</td>\n      <td>29</td>\n      <td>68</td>\n      <td>79</td>\n      <td>4</td>\n      <td>28</td>\n      <td>33</td>\n      <td>34</td>\n      <td>226</td>\n      <td>229</td>\n      <td>24</td>\n      <td>115</td>\n      <td>1172</td>\n      <td>74</td>\n      <td>58</td>\n      <td>400</td>\n      <td>1646</td>\n      <td>86</td>\n      <td>183</td>\n      <td>9</td>\n      <td>75</td>\n      <td>254</td>\n      <td>218</td>\n      <td>1534</td>\n      <td>393</td>\n      <td>265</td>\n      <td>99</td>\n      <td>93</td>\n      <td>42</td>\n      <td>12</td>\n      <td>51</td>\n      <td>253</td>\n      <td>13</td>\n      <td>158</td>\n      <td>62</td>\n      <td>230</td>\n      <td>156</td>\n      <td>293</td>\n      <td>131</td>\n      <td>543</td>\n      <td>170</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>2005</td>\n      <td>14</td>\n      <td>33</td>\n      <td>137</td>\n      <td>137</td>\n      <td>31</td>\n      <td>62</td>\n      <td>79</td>\n      <td>4</td>\n      <td>28</td>\n      <td>31</td>\n      <td>35</td>\n      <td>205</td>\n      <td>224</td>\n      <td>24</td>\n      <td>119</td>\n      <td>1203</td>\n      <td>79</td>\n      <td>57</td>\n      <td>401</td>\n      <td>1632</td>\n      <td>85</td>\n      <td>195</td>\n      <td>9</td>\n      <td>79</td>\n      <td>259</td>\n      <td>223</td>\n      <td>1671</td>\n      <td>401</td>\n      <td>280</td>\n      <td>104</td>\n      <td>97</td>\n      <td>47</td>\n      <td>12</td>\n      <td>55</td>\n      <td>265</td>\n      <td>13</td>\n      <td>167</td>\n      <td>78</td>\n      <td>234</td>\n      <td>156</td>\n      <td>311</td>\n      <td>147</td>\n      <td>571</td>\n      <td>175</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>2006</td>\n      <td>14</td>\n      <td>34</td>\n      <td>136</td>\n      <td>139</td>\n      <td>30</td>\n      <td>61</td>\n      <td>78</td>\n      <td>4</td>\n      <td>28</td>\n      <td>32</td>\n      <td>33</td>\n      <td>187</td>\n      <td>216</td>\n      <td>26</td>\n      <td>128</td>\n      <td>1227</td>\n      <td>82</td>\n      <td>59</td>\n      <td>418</td>\n      <td>1655</td>\n      <td>86</td>\n      <td>207</td>\n      <td>10</td>\n      <td>84</td>\n      <td>259</td>\n      <td>226</td>\n      <td>1793</td>\n      <td>406</td>\n      <td>314</td>\n      <td>105</td>\n      <td>94</td>\n      <td>48</td>\n      <td>12</td>\n      <td>57</td>\n      <td>270</td>\n      <td>13</td>\n      <td>165</td>\n      <td>81</td>\n      <td>233</td>\n      <td>156</td>\n      <td>323</td>\n      <td>151</td>\n      <td>565</td>\n      <td>185</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>2007</td>\n      <td>14</td>\n      <td>34</td>\n      <td>135</td>\n      <td>136</td>\n      <td>31</td>\n      <td>60</td>\n      <td>72</td>\n      <td>5</td>\n      <td>28</td>\n      <td>31</td>\n      <td>33</td>\n      <td>176</td>\n      <td>215</td>\n      <td>27</td>\n      <td>132</td>\n      <td>1239</td>\n      <td>83</td>\n      <td>60</td>\n      <td>420</td>\n      <td>1670</td>\n      <td>83</td>\n      <td>217</td>\n      <td>9</td>\n      <td>87</td>\n      <td>248</td>\n      <td>199</td>\n      <td>1917</td>\n      <td>425</td>\n      <td>318</td>\n      <td>94</td>\n      <td>94</td>\n      <td>47</td>\n      <td>13</td>\n      <td>60</td>\n      <td>286</td>\n      <td>14</td>\n      <td>164</td>\n      <td>85</td>\n      <td>236</td>\n      <td>157</td>\n      <td>337</td>\n      <td>147</td>\n      <td>546</td>\n      <td>183</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>2008</td>\n      <td>14</td>\n      <td>33</td>\n      <td>137</td>\n      <td>133</td>\n      <td>33</td>\n      <td>68</td>\n      <td>71</td>\n      <td>4</td>\n      <td>29</td>\n      <td>30</td>\n      <td>33</td>\n      <td>167</td>\n      <td>222</td>\n      <td>29</td>\n      <td>144</td>\n      <td>1254</td>\n      <td>84</td>\n      <td>62</td>\n      <td>409</td>\n      <td>1702</td>\n      <td>83</td>\n      <td>229</td>\n      <td>10</td>\n      <td>93</td>\n      <td>228</td>\n      <td>200</td>\n      <td>1967</td>\n      <td>445</td>\n      <td>323</td>\n      <td>92</td>\n      <td>97</td>\n      <td>50</td>\n      <td>13</td>\n      <td>66</td>\n      <td>287</td>\n      <td>15</td>\n      <td>162</td>\n      <td>89</td>\n      <td>232</td>\n      <td>160</td>\n      <td>338</td>\n      <td>153</td>\n      <td>573</td>\n      <td>186</td>\n    </tr>\n    <tr>\n      <th>19</th>\n      <td>2009</td>\n      <td>15</td>\n      <td>32</td>\n      <td>129</td>\n      <td>126</td>\n      <td>32</td>\n      <td>63</td>\n      <td>67</td>\n      <td>5</td>\n      <td>28</td>\n      <td>30</td>\n      <td>30</td>\n      <td>158</td>\n      <td>217</td>\n      <td>30</td>\n      <td>148</td>\n      <td>1190</td>\n      <td>79</td>\n      <td>57</td>\n      <td>394</td>\n      <td>1686</td>\n      <td>81</td>\n      <td>231</td>\n      <td>10</td>\n      <td>98</td>\n      <td>224</td>\n      <td>200</td>\n      <td>2052</td>\n      <td>484</td>\n      <td>351</td>\n      <td>98</td>\n      <td>91</td>\n      <td>49</td>\n      <td>13</td>\n      <td>65</td>\n      <td>295</td>\n      <td>15</td>\n      <td>153</td>\n      <td>88</td>\n      <td>225</td>\n      <td>158</td>\n      <td>334</td>\n      <td>130</td>\n      <td>519</td>\n      <td>172</td>\n    </tr>\n    <tr>\n      <th>20</th>\n      <td>2010</td>\n      <td>16</td>\n      <td>32</td>\n      <td>136</td>\n      <td>129</td>\n      <td>33</td>\n      <td>71</td>\n      <td>67</td>\n      <td>6</td>\n      <td>28</td>\n      <td>35</td>\n      <td>33</td>\n      <td>148</td>\n      <td>203</td>\n      <td>32</td>\n      <td>157</td>\n      <td>1279</td

In [43]:
# Save path to data set in a variable
data_file9 = "C:\\Users\\taiwo\\OneDrive\\Desktop\\PREWORK_TO\\Module 16\\Project2\\Data Files\\EBOT2.csv"

In [45]:
# Use Pandas to read data
data_file_pd9 = pd.read_csv(data_file9)
data_file_pd9.head()

,Year,Belgium,Czech Republic,France,Germany,Italy,Netherlands,Poland,Portugal,Romania,...,Australia,New Zealand,Algeria,Egypt,Nigeria,South Africa,Iran,Kuwait,Saudi Arabia,United Arab Emirates
0,1990,39.7,7.6,120.0,167.1,131.6,19.0,1.3,15.3,22.0,...,-63.4,2.1,-77.3,-20.8,-79.4,-21.9,-117.6,-41.3,-307.0,-80.5
1,1991,42.4,7.0,126.8,181.0,130.9,15.5,1.4,15.2,14.5,...,-78.7,1.9,-78.5,-20.8,-82.4,-21.7,-122.6,-7.6,-391.9,-91.2
2,1992,43.4,7.0,124.5,187.9,133.4,15.2,1.9,16.7,13.7,...,-81.8,2.0,-79.6,-22.9,-85.2,-23.8,-133.0,-50.5,-395.8,-99.1
3,1993,41.8,6.8,116.4,189.6,127.3,14.4,3.0,16.0,12.3,...,-83.3,2.0,-80.0,-23.5,-86.5,-26.4,-139.6,-93.9,-387.5,-95.0
4,1994,45.7,7.7,113.4,193.2,126.3,18.7,0.7,16.3,11.0,...,-82.3,2.8,-76.8,-23.3,-89.2,-27.0,-133.4,-98.6,-373.9,-93.7

In [46]:
#convert dataframe to HTML - EBOT2
html_table = data_file_pd9.to_html()
html_table

'<table border="1" class="dataframe">\n  <thead>\n    <tr style="text-align: right;">\n      <th></th>\n      <th>Year</th>\n      <th>Belgium</th>\n      <th>Czech Republic</th>\n      <th>France</th>\n      <th>Germany</th>\n      <th>Italy</th>\n      <th>Netherlands</th>\n      <th>Poland</th>\n      <th>Portugal</th>\n      <th>Romania</th>\n      <th>Spain</th>\n      <th>Sweden</th>\n      <th>United Kingdom</th>\n      <th>Norway</th>\n      <th>Turkey</th>\n      <th>Kazakhstan</th>\n      <th>Russia</th>\n      <th>Ukraine</th>\n      <th>Uzbekistan</th>\n      <th>Canada</th>\n      <th>United States</th>\n      <th>Argentina</th>\n      <th>Brazil</th>\n      <th>Chile</th>\n      <th>Colombia</th>\n      <th>Mexico</th>\n      <th>Venezuela</th>\n      <th>China</th>\n      <th>India</th>\n      <th>Indonesia</th>\n      <th>Japan</th>\n      <th>Malaysia</th>\n      <th>South Korea</th>\n      <th>Taiwan</th>\n      <th>Thailand</th>\n      <th>Australia</th>\n      <th>New Zealand</th>\n      <th>Algeria</th>\n      <th>Egypt</th>\n      <th>Nigeria</th>\n      <th>South Africa</th>\n      <th>Iran</th>\n      <th>Kuwait</th>\n      <th>Saudi Arabia</th>\n      <th>United Arab Emirates</th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>0</th>\n      <td>1990</td>\n      <td>39.7</td>\n      <td>7.6</td>\n      <td>120.0</td>\n      <td>167.1</td>\n      <td>131.6</td>\n      <td>19.0</td>\n      <td>1.3</td>\n      <td>15.3</td>\n      <td>22.0</td>\n      <td>60.2</td>\n      <td>17.5</td>\n      <td>4.7</td>\n      <td>-95.7</td>\n      <td>28.0</td>\n      <td>-16.6</td>\n      <td>-412.7</td>\n      <td>120.8</td>\n      <td>7.7</td>\n      <td>-59.4</td>\n      <td>342.0</td>\n      <td>-1.4</td>\n      <td>39.4</td>\n      <td>7.0</td>\n      <td>-21.2</td>\n      <td>-69.9</td>\n      <td>-101.9</td>\n      <td>-35.0</td>\n      <td>31.6</td>\n      <td>-69.0</td>\n      <td>377.2</td>\n      <td>-25.9</td>\n      <td>70.2</td>\n      <td>41.7</td>\n      <td>17.8</td>\n      <td>-63.4</td>\n      <td>2.1</td>\n      <td>-77.3</td>\n      <td>-20.8</td>\n      <td>-79.4</td>\n      <td>-21.9</td>\n      <td>-117.6</td>\n      <td>-41.3</td>\n      <td>-307.0</td>\n      <td>-80.5</td>\n    </tr>\n    <tr>\n      <th>1</th>\n      <td>1991</td>\n      <td>42.4</td>\n      <td>7.0</td>\n      <td>126.8</td>\n      <td>181.0</td>\n      <td>130.9</td>\n      <td>15.5</td>\n      <td>1.4</td>\n      <td>15.2</td>\n      <td>14.5</td>\n      <td>63.1</td>\n      <td>16.9</td>\n      <td>11.2</td>\n      <td>-109.2</td>\n      <td>24.8</td>\n      <td>-16.1</td>\n      <td>-346.2</td>\n      <td>135.5</td>\n      <td>9.0</td>\n      <td>-76.4</td>\n      <td>322.3</td>\n      <td>-1.8</td>\n      <td>39.9</td>\n      <td>7.3</td>\n      <td>-22.1</td>\n      <td>-72.7</td>\n      <td>-117.0</td>\n      <td>-30.5</td>\n      <td>35.1</td>\n      <td>-78.9</td>\n      <td>374.5</td>\n      <td>-24.9</td>\n      <td>81.6</td>\n      <td>41.8</td>\n      <td>18.1</td>\n      <td>-78.7</td>\n      <td>1.9</td>\n      <td>-78.5</td>\n      <td>-20.8</td>\n      <td>-82.4</td>\n      <td>-21.7</td>\n      <td>-122.6</td>\n      <td>-7.6</td>\n      <td>-391.9</td>\n      <td>-91.2</td>\n    </tr>\n    <tr>\n      <th>2</th>\n      <td>1992</td>\n      <td>43.4</td>\n      <td>7.0</td>\n      <td>124.5</td>\n      <td>187.9</td>\n      <td>133.4</td>\n      <td>15.2</td>\n      <td>1.9</td>\n      <td>16.7</td>\n      <td>13.7</td>\n      <td>67.3</td>\n      <td>16.9</td>\n      <td>8.8</td>\n      <td>-123.6</td>\n      <td>26.9</td>\n      <td>-9.9</td>\n      <td>-331.2</td>\n      <td>111.7</td>\n      <td>4.7</td>\n      <td>-83.9</td>\n      <td>356.8</td>\n      <td>-3.2</td>\n      <td>39.9</td>\n      <td>7.7</td>\n      <td>-20.1</td>\n      <td>-70.6</td>\n      <td>-104.6</td>\n      <td>-23.2</td>\n      <td>42.1</td>\n      <td>-79.2</td>\n      <td>385.0</td>\n      <td>-24.9</td>\n      <td>97.5</td>\n      <td>46.6</td>\n      <td>20.9</td>\n      <td>-81.8</td>\n      <td>2.0</td>\n      <td>-79.6</td>\n      <td>-22.9</td>\n      <td>-85.2</td>\n      <td>-23.8</td>\n      <td>-133.0</td>\n      <td>-50.5</td>\n      <td>-395.8</td>\n      <td>-99.1</td>\n    </tr>\n    <tr>\n      <th>3</th>\n      <td>1993</td>\n      <td>41.8</td>\n      <td>6.8</td>\n      <td>116.4</td>\n      <td>189.6</td>\n      <td>127.3</td>\n      <td>14.4</td>\n      <td>3.0</td>\n      <td>16.0</td>\n      <td>12.3</td>\n      <td>64.3</td>\n      <td>17.6</td>\n      <td>0.4</td>\n      <td>-130.0</td>\n      <td>31.5</td>\n      <td>-13.0</td>\n      <td>-292.9</td>\n      <td>90.3</td>\n      <td>4.2</td>\n      <td>-93.9</td>\n      <td>418.1</td>\n      <td>-4.9</td>\n      <td>45.9</td>\n      <td>8.1</td>\n      <td>-23.0</td>\n      <td>-72.0</td>\n      <td>-127.2</td>\n      <td>-3.4</td>\n      <td>44.8</td>\n      <td>-75.2</td>\n      <td>381.5</td>\n      <td>-23.0</td>\n      <td>111.9</td>\n      <td>50.5</td>\n      <td>24.7</td>\n      <td>-83.3</td>\n      <td>2.0</td>\n      <td>-80.0</td>\n      <td>-23.5</td>\n      <td>-86.5</td>\n      <td>-26.4</td>\n      <td>-139.6</td>\n      <td>-93.9</td>\n      <td>-387.5</td>\n      <td>-95.0</td>\n    </tr>\n    <tr>\n      <th>4</th>\n      <td>1994</td>\n      <td>45.7</td>\n      <td>7.7</td>\n      <td>113.4</td>\n      <td>193.2</td>\n      <td>126.3</td>\n      <td>18.7</td>\n      <td>0.7</td>\n      <td>16.3</td>\n      <td>11.0</td>\n      <td>69.2</td>\n      <td>19.6</td>\n      <td>-33.0</td>\n      <td>-146.1</td>\n      <td>31.3</td>\n      <td>-12.7</td>\n      <td>-314.0</td>\n      <td>75.5</td>\n      <td>0.4</td>\n      <td>-106.8</td>\n      <td>449.0</td>\n      <td>-8.9</td>\n      <td>47.0</td>\n      <td>10.0</td>\n      <td>-23.2</td>\n      <td>-66.4</td>\n      <td>-131.3</td>\n      <td>-14.2</td>\n      <td>45.9</td>\n      <td>-88.3</td>\n      <td>407.9</td>\n      <td>-24.4</td>\n      <td>124.7</td>\n      <td>54.1</td>\n      <td>28.1</td>\n      <td>-82.3</td>\n      <td>2.8</td>\n      <td>-76.8</td>\n      <td>-23.3</td>\n      <td>-89.2</td>\n      <td>-27.0</td>\n      <td>-133.4</td>\n      <td>-98.6</td>\n      <td>-373.9</td>\n      <td>-93.7</td>\n    </tr>\n    <tr>\n      <th>5</th>\n      <td>1995</td>\n      <td>47.0</td>\n      <td>8.6</td>\n      <td>118.1</td>\n      <td>195.4</td>\n      <td>134.4</td>\n      <td>18.1</td>\n      <td>0.1</td>\n      <td>18.1</td>\n      <td>14.3</td>\n      <td>76.4</td>\n      <td>18.5</td>\n      <td>-37.2</td>\n      <td>-159.9</td>\n      <td>36.6</td>\n      <td>-11.3</td>\n      <td>-315.1</td>\n      <td>82.3</td>\n      <td>-4.0</td>\n      <td>-119.7</td>\n      <td>433.2</td>\n      <td>-12.2</td>\n      <td>48.4</td>\n      <td>10.8</td>\n      <td>-29.3</td>\n      <td>-69.3</td>\n      <td>-144.0</td>\n      <td>-12.7</td>\n      <td>53.4</td>\n      <td>-83.6</td>\n      <td>408.4</td>\n      <td>-28.3</td>\n      <td>134.8</td>\n      <td>59.5</td>\n      <td>32.1</td>\n      <td>-88.0</td>\n      <td>3.1</td>\n      <td>-82.0</td>\n      <td>-22.0</td>\n      <td>-90.8</td>\n      <td>-27.6</td>\n      <td>-135.2</td>\n      <td>-99.2</td>\n      <td>-376.0</td>\n      <td>-95.6</td>\n    </tr>\n    <tr>\n      <th>6</th>\n      <td>1996</td>\n      <td>49.6</td>\n      <td>10.4</td>\n      <td>123.5</td>\n      <td>208.6</td>\n      <td>133.9</td>\n      <td>16.5</td>\n      <td>6.1</td>\n      <td>16.9</td>\n      <td>14.7</td>\n      <td>74.7</td>\n      <td>20.3</td>\n      <td>-34.4</td>\n      <td>-182.3</td>\n      <td>40.7</td>\n      <td>-18.1</td>\n      <td>-334.5</td>\n      <td>76.7</td>\n      <td>-4.9</td>\n      <td>-120.6</td>\n      <td>466.1</td>\n      <td>-15.3</td>\n      <td>54.5</td>\n      <td>13.0</td>\n      <td>-35.2</td>\n      <td>-75.9</td>\n      <td>-161.0</td>\n      <td>-11.8</td>\n      <td>61.1</td>\n      <td>-87.9</td>\n      <td>416.5</td>\n      <td>-30.8</td>\n      <td>147.3</td>\n      <td>61.6</td>\n      <td>36.6</td>\n      <td>-88.9</td>\n      <td>2.8</td>\n      <td>-88.6</td>\n      <td>-18.0</td>\n      <td>-100.2</td>\n      <td>-26.0</td>\n      <td>-136.3</td>\n      <td>-99.7</td>\n      <td>-375.1</td>\n      <td>-97.2</td>\n    </tr>\n    <tr>\n      <th>7</th>\n      <td>1997</td>\n      <td>49.1</td>\n      <td>10.5</td>\n      <td>122.5</td>\n      <td>209.3</td>\n      <td>133.9</td>\n      <td>25.3</td>\n      <td>6.8</td>\n      <td>18.4</td>\n      <td>14.6</td>\n      <td>81.0</td>\n      <td>18.8</td>\n      <td>-35.4</td>\n      <td>-188.0</td>\n      <td>42.6</td>\n      <td>-25.8</td>\n      <td>-339.8</td>\n      <td>69.1</td>\n      <td>-7.0</td>\n      <td>-121.9</td>\n      <td>505.4</td>\n      <td>-17.4</td>\n      <td>55.5</td>\n      <td>14.7</td>\n      <td>-37.9</td>\n      <td>-80.6</td>\n      <td>-179.1</td>\n      <td>7.4</td>\n      <td>67.4</td>\n      <td>-86.7</td>\n      <td>416.9</td>\n      <td>-28.2</td>\n      <td>160.2</td>\n      <td>65.2</td>\n      <td>34.4</td>\n      <td>-102.0</td>\n      <td>2.7</td>\n      <td>-97.1</td>\n      <td>-15.4</td>\n      <td>-108.4</td>\n      <td>-30.2</td>\n      <td>-127.2</td>\n      <td>-99.3</td>\n      <td>-374.5</td>\n      <td>-102.6</td>\n    </tr>\n    <tr>\n      <th>8</th>\n      <td>1998</td>\n      <td>51.8</td>\n      <td>10.6</td>\n      <td>132.3</td>\n      <td>214.0</td>\n      <td>139.7</td>\n      <td>26.8</td>\n      <td>8.2</td>\n      <td>20.0</td>\n      <td>11.7</td>\n      <td>88.6</td>\n      <td>19.0</td>\n      <td>-38.4</td>\n      <td>-180.4</td>\n      <td>43.3</td>\n      <td>-25.2</td>\n      <td>-346.6</td>\n      <td>61.3</td>\n      <td>-4.6</td>\n      <td>-128.0</td>\n      <td>541.9</td>\n      <td>-17.9</td>\n      <td>52.1</td>\n      <td>16.4</td>\n      <td>-44.3</td>\n      <td>-77.1</td>\n      <td>-173.6</td>\n      <td>3.1</td>\n      <td>74.5</td>\n      <td>-91.0</td>\n      <td>401.8</td>\n      <td>-30.7</td>\n      <td>141.6</td>\n      <td>69.2</td>\n      <td>29.8</td>\n      <td>-111.6</td>\n      <td>3.4</td>\n      <td>-101.6</td>\n      <td>-13.1</td>\n      <td>-97.5</td>\n      <td>-24.0</td>\n      <td>-128.5</td>\n      <td>-99.4</td>\n      <td>-383.0</td>\n      <td>-105.2</td>\n    </tr>\n    <tr>\n      <th>9</th>\n      <td>1999</td>\n      <td>48.9</td>\n      <td>10.0</td>\n      <td>133.8</td>\n      <td>203.5</td>\n      <td>143.3</td>\n      <td>28.8</td>\n      <td>9.3</td>\n      <td>22.5</td>\n      <td>7.6</td>\n      <td>95.1</td>\n      <td>17.3</td>\n      <td>-48.2</td>\n      <td>-182.5</td>\n      <td>43.2</td>\n      <td>-31.0</td>\n      <td>-352.1</td>\n      <td>59.8</td>\n      <td>-3.8</td>\n      <td>-125.9</td>\n      <td>572.0</td>\n      <td>-18.6</td>\n      <td>47.8</td>\n      <td>17.8</td>\n      <td>-49.7</td>\n      <td>-70.7</td>\n      <td>-156.7</td>\n      <td>14.0</td>\n      <td>87.0</td>\n      <td>-93.0</td>\n      <td>412.2</td>\n      <td>-28.7</td>\n      <td>152.9</td>\n      <td>73.2</td>\n      <td>32.0</td>\n      <td>-109.8</td>\n      <td>3.4</td>\n      <td>-109.5</td>\n      <td>-13.8</td>\n      <td>-99.6</td>\n      <td>-30.7</td>\n      <td>-122.5</td>\n      <td>-88.7</td>\n      <td>-344.9</td>\n      <td>-96.9</td>\n    </tr>\n    <tr>\n      <th>10</th>\n      <td>2000</td>\n      <td>50.7</td>\n      <td>9.5</td>\n      <td>135.7</td>\n      <td>205.5</td>\n      <td>152.5</td>\n      <td>36.2</td>\n      <td>9.6</td>\n      <td>22.1</td>\n      <td>7.8</td>\n      <td>100.2</td>\n      <td>18.3</td>\n      <td>-40.2</td>\n      <td>-200.3</td>\n      <td>50.9</td>\n      <td>-42.8</td>\n      <td>-349.6</td>\n      <td>57.6</td>\n      <td>-4.2</td>\n      <td>-130.1</td>\n      <td>606.2</td>\n      <td>-20.3</td>\n      <td>44.4</td>\n      <td>17.7</td>\n      <td>-46.4</td>\n      <td>-71.9</td>\n      <td>-163.2</td>\n      <td>27.9</td>\n      <td>91.4</td>\n      <td>-81.2</td>\n      <td>428.7</td>\n      <td>-27.4</td>\n      <td>165.8</td>\n      <td>79.2</td>\n      <td>32.1</td>\n      <td>-127.1</td>\n      <td>3.4</td>\n      <td>-115.0</td>\n      <td>-9.7</td>\n      <td>-110.1</td>\n      <td>-31.8</td>\n      <td>-130.2</td>\n      <td>-95.1</td>\n      <td>-373.9</td>\n      <td>-109.9</td>\n    </tr>\n    <tr>\n      <th>11</th>\n      <td>2001</td>\n      <td>51.9</td>\n      <td>10.7</td>\n      <td>134.4</td>\n      <td>216.8</td>\n      <td>146.9</td>\n      <td>34.0</td>\n      <td>9.5</td>\n      <td>22.0</td>\n      <td>9.6</td>\n      <td>100.6</td>\n      <td>18.3</td>\n      <td>-22.4</td>\n      <td>-200.9</td>\n      <td>46.0</td>\n      <td>-46.4</td>\n      <td>-369.9</td>\n      <td>58.0</td>\n      <td>-4.5</td>\n      <td>-131.1</td>\n      <td>644.7</td>\n      <td>-25.3</td>\n      <td>40.2</td>\n      <td>16.8</td>\n      <td>-44.6</td>\n      <td>-74.8</td>\n      <td>-153.4</td>\n      <td>1.1</td>\n      <td>91.6</td>\n      <td>-81.9</td>\n      <td>413.4</td>\n      <td>-26.1</td>\n      <td>164.7</td>\n      <td>81.8</td>\n      <td>34.8</td>\n      <td>-133.7</td>\n      <td>3.3</td>\n      <td>-109.9</td>\n      <td>-8.5</td>\n      <td>-115.5</td>\n      <td>-34.2</td>\n      <td>-116.3</td>\n      <td>-91.4</td>\n      <td>-359.6</td>\n      <td>-103.1</td>\n    </tr>\n    <tr>\n      <th>12</th>\n      <td>2002</td>\n      <td>49.4</td>\n      <td>11.2</td>\n      <td>135.7</td>\n      <td>209.5</td>\n      <td>152.2</td>\n      <td>33.9</td>\n      <td>10.1</td>\n      <td>22.6</td>\n      <td>9.2</td>\n      <td>108.7</td>\n      <td>20.0</td>\n      <td>-27.6</td>\n      <td>-209.0</td>\n      <td>51.2</td>\n      <td>-51.3</td>\n      <td>-412.6</td>\n      <td>59.1</td>\n      <td>-3.1</td>\n      <td>-136.0</td>\n      <td>628.9</td>\n      <td>-24.6</td>\n      <td>30.7</td>\n      <td>17.7</td>\n      <td>-42.4</td>\n      <td>-77.3</td>\n      <td>-145.0</td>\n      <td>19.4</td>\n      <td>96.8</td>\n      <td>-82.5</td>\n      <td>423.4</td>\n      <td>-27.2</td>\n      <td>172.2</td>\n      <td>84.0</td>\n      <td>38.8</td>\n      <td>-139.6</td>\n      <td>3.7</td>\n      <td>-113.3</td>\n      <td>-9.4</td>\n      <td>-99.0</td>\n      <td>-35.4</td>\n      <td>-116.9</td>\n      <td>-79.7</td>\n      <td>-315.5</td>\n      <td>-97.2</td>\n    </tr>\n    <tr>\n      <th>13</th>\n      <td>2003</td>\n      <td>53.2</td>\n      <td>11.2</td>\n      <td>138.8</td>\n      <td>210.5</td>\n      <td>154.8</td>\n      <td>38.9</td>\n      <td>12.0</td>\n      <td>22.5</td>\n      <td>9.9</td>\n      <td>109.7</td>\n      <td>22.9</td>\n      <td>-14.0</td>\n      <td>-206.0</td>\n      <td>56.5</td>\n      <td>-58.3</td>\n      <td>-458.3</td>\n      <td>65.5</td>\n      <td>-5.0</td>\n      <td>-129.0</td>\n      <td>661.3</td>\n      <td>-24.1</td>\n      <td>25.1</td>\n      <td>18.4</td>\n      <td>-45.6</td>\n      <td>-83.3</td>\n      <td>-125.1</td>\n      <td>40.1</td>\n      <td>99.8</td>\n      <td>-88.6</td>\n      <td>432.7</td>\n      <td>-28.1</td>\n      <td>177.6</td>\n      <td>87.6</td>\n      <td>42.9</td>\n      <td>-138.7</td>\n      <td>4.4</td>\n      <td>-123.6</td>\n      <td>-9.8</td>\n      <td>-115.8</td>\n      <td>-31.3</td>\n      <td>-136.7</td>\n      <td>-98.1</td>\n      <td>-388.9</td>\n      <td>-110.5</td>\n    </tr>\n    <tr>\n      <th>14</th>\n      <td>2004</td>\n      <td>53.7</td>\n      <td>11.7</td>\n      <td>141.8</td>\n      <td>214.0</td>\n      <td>158.4</td>\n      <td>33.0</td>\n      <td>13.4</td>\n      <td>22.8</td>\n      <td>11.5</td>\n      <td>115.9</td>\n      <td>20.4</td>\n      <td>10.8</td>\n      <td>-201.9</td>\n      <td>58.1</td>\n      <td>-64.0</td>\n      <td>-514.4</td>\n      <td>64.3</td>\n      <td>-7.3</td>\n      <td>-134.3</td>\n      <td>713.4</td>\n      <td>-18.7</td>\n      <td>31.3</td>\n      <td>20.7</td>\n      <td>-48.7</td>\n      <td>-82.5</td>\n      <td>-160.9</td>\n      <td>94.0</td>\n      <td>108.8</td>\n      <td>-87.9</td>\n      <td>437.4</td>\n      <td>-28.8</td>\n      <td>183.4</td>\n      <td>96.3</td>\n      <td>48.9</td>\n      <td>-141.8</td>\n      <td>5.3</td>\n      <td>-126.2</td>\n      <td>-6.3</td>\n      <td>-130.6</td>\n      <td>-27.3</td>\n      <td>-136.0</td>\n      <td>-106.9</td>\n      <td>-421.1</td>\n      <td>-114.0</td>\n    </tr>\n    <tr>\n      <th>15</th>\n      <td>2005</td>\n      <td>53.7</td>\n      <td>12.7</td>\n      <td>144.7</td>\n      <td>211.4</td>\n      <td>159.5</td>\n      <td>38.6</td>\n      <td>16.3</td>\n      <td>24.5</td>\n      <td>10.5</td>\n      <td>124.6</td>\n      <td>20.4</td>\n      <td>31.9</td>\n      <td>-195.9</td>\n      <td>61.8</td>\n      <td>-68.1</td>\n      <td>-539.5</td>\n      <td>59.7</td>\n      <td>-9.4</td>\n      <td>-129.5</td>\n      <td>735.8</td>\n      <td>-16.2</td>\n      <td>24.9</td>\n      <td>20.5</td>\n      <td>-50.2</td>\n      <td>-76.9</td>\n      <td>-174.5</td>\n      <td>100.2</td>\n      <td>121.5</td>\n      <td>-99.7</td>\n      <td>435.4</td>\n      <td>-28.4</td>\n      <td>175.6</td>\n      <td>95.3</td>\n      <td>47.9</td>\n      <td>-148.7</td>\n      <td>4.9</td>\n      <td>-133.7</td>\n      <td>-14.2</td>\n      <td>-127.9</td>\n      <td>-30.2</td>\n      <td>-138.5</td>\n      <td>-118.4</td>\n      <td>-444.3</td>\n      <td>-116.2</td>\n    </tr>\n    <tr>\n      <th>16</th>\n      <td>2006</td>\n      <td>53.5</td>\n      <td>12.9</td>\n      <td>142.1</td>\n      <td>218.7</td>\n      <td>162.9</td>\n      <td>39.1</td>\n      <td>19.6</td>\n      <td>22.3</td>\n      <td>11.6</td>\n      <td>124.7</td>\n      <td>20.0</td>\n      <td>49.5</td>\n      <td>-186.7</td>\n      <td>69.0</td>\n      <td>-66.6</td>\n      <td>-538.5</td>\n      <td>56.2</td>\n      <td>-10.5</td>\n      <td>-138.4</td>\n      <td>729.2</td>\n      <td>-11.7</td>\n      <td>20.6</td>\n      <td>21.5</td>\n      <td>-55.3</td>\n      <td>-73.4</td>\n      <td>-169.4</td>\n      <td>136.0</td>\n      <td>135.5</td>\n      <td>-129.5</td>\n      <td>429.7</td>\n      <td>-25.3</td>\n      <td>186.0</td>\n      <td>98.3</td>\n      <td>47.9</td>\n      <td>-146.1</td>\n      <td>4.8</td>\n      <td>-129.6</td>\n      <td>-14.0</td>\n      <td>-126.6</td>\n      <td>-26.8</td>\n      <td>-138.8</td>\n      <td>-123.0</td>\n      <td>-427.2</td>\n      <td>-122.9</td>\n    </tr>\n    <tr>\n      <th>17</th>\n      <td>2007</td>\n      <td>51.8</td>\n      <td>11.6</td>\n      <td>137.9</td>\n      <td>200.0</td>\n      <td>157.7</td>\n      <td>39.0</td>\n      <td>25.0</td>\n      <td>21.7</td>\n      <td>12.5</td>\n      <td>123.9</td>\n      <td>19.2</td>\n      <td>46.3</td>\n      <td>-187.3</td>\n      <td>75.8</td>\n      <td>-65.9</td>\n      <td>-552.6</td>\n      <td>57.3</td>\n      <td>-12.2</td>\n      <td>-150.0</td>\n      <td>713.2</td>\n      <td>-8.2</td>\n      <td>25.0</td>\n      <td>23.9</td>\n      <td>-56.0</td>\n      <td>-61.5</td>\n      <td>-139.0</td>\n      <td>167.1</td>\n      <td>148.9</td>\n      <td>-135.1</td>\n      <td>435.0</td>\n      <td>-18.7</td>\n      <td>190.3</td>\n      <td>101.6</td>\n      <td>48.9</td>\n      <td>-155.4</td>\n      <td>4.3</td>\n      <td>-127.5</td>\n      <td>-13.8</td>\n      <td>-128.0</td>\n      <td>-18.9</td>\n      <td>-141.9</td>\n      <td>-118.4</td>\n      <td>-401.6</td>\n      <td>-115.5</td>\n    </tr>\n    <tr>\n      <th>18</th>\n      <td>2008</td>\n      <td>56.1</td>\n      <td>12.7</td>\n      <td>139.4</td>\n      <td>210.3</td>\n      <td>155.3</td>\n      <td>34.9</td>\n      <td>30.2</td>\n      <td>21.8</td>\n      <td>10.9</td>\n      <td>123.1</td>\n      <td>19.9</td>\n      <td>58.5</td>\n      <td>-188.0</td>\n      <td>72.5</td>\n      <td>-74.9</td>\n      <td>-536.8</td>\n      <td>57.2</td>\n      <td>-12.4</td>\n      <td>-142.2</td